Project The Greenery/TheGreenery/TheGreenery/Controllers/BeheerderController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheGreenery.DBcontrollers;
using TheGreenery.Models;
using MySql.Data.MySqlClient;


namespace TheGreenery.Controllers
{
    public class BeheerderController : DatabaseController
    {

        public ActionResult Ingelogd()
        {
            return View();
        }

        public ActionResult ProductenToevoegen()
        {
            if (Session["LoggedInP"] != null)
            {
                Personeel p = Session["LoggedInP"] as Personeel;
                return View(p);
            }
            else
            {
                String urlLogin = "/Personeel/PersoneelLogIn";
                return Redirect(urlLogin);
            }
        }

        public ActionResult ProductToegevoegd(String naam, String type, String lente, String zomer, String herfst, String winter, double prijsPerEenheid,
                                       String eenheid, String omschrijving, int voorraadPerEenheid, String imageNaam, String aanbieding)
        {
            if (Session["LoggedInP"] != null)
            {
            Product product = new Product();
            product.setNaam(naam);
            product.setType(type);
            product.setLente(lente);
            product.setZomer(zomer);
            product.setHerfst(herfst);
            product.setWinter(winter);
            product.setPrijsPerEenheid(prijsPerEenheid);
            product.setEenheid(eenheid);
            product.setOmschrijving(omschrijving);
            product.setVoorraadPerEenheid(voorraadPerEenheid);
            product.setImageNaam(imageNaam);
            product.setAanbieding(aanbieding);

            ProductDBController productToevoegenController = new ProductDBController();
            productToevoegenController.InsertProduct(product);

                return View(product);

            }
            else
            {
                String urlLogin = "/Personeel/PersoneelLogIn";
                return Redirect(urlLogin);
            }

        }

        public ActionResult ProductenBewerken(String naam)
        {
            if (Session["LoggedInP"] != null)
            {
                ProductDBController sc = new ProductDBController();
                List<Product> producten = sc.getAllProducten(naam);
                return View(producten);

            }
             
            else
            {
                String urlLogin = "/Personeel/PersoneelLogIn";
                return Redirect(urlLogin);
            }
        }

        public ActionResult ProductAangepast(String naam, String type, String lente, String zomer, String herfst, String winter, double? prijsPerEenheid,
                                       String eenheid, String omschrijving, int? voorraadPerEenheid, String imageNaam, String aanbieding)
        {
            if (Session["LoggedInP"] != null)
            {
                Product product = new Product();
                product.setNaam(naam);
                product.setType(type);
                product.setLente(lente);
                product.setZomer(zomer);
                product.setHerfst(herfst);
                product.setWinter(winter);
                product.setPrijsPerEenheid(prijsPerEenheid);
                product.setEenheid(eenheid);
                product.setOmschrijving(omschrijving);
                product.setVoorraadPerEenheid(voorraadPerEenheid);
                product.setImageNaam(imageNaam);
                product.setAanbieding(aanbieding);

                //ProductDBController productToevoegenController = new ProductDBController();
                //productToevoegenController.InsertProduct(product);

                return View(product);

            }
            else
            {
                String urlLogin = "/Personeel/PersoneelLogIn";
                return Redirect(urlLogin);
            }
        }

        public ActionResult PersoneelToevoegen(String voorletters, String tussenvoegsel, String achternaam, String type, String wachtwoord)
        {
            if (Session["LoggedInP"] != null)
            {
                Personeel p = Session["LoggedInP"] as Personeel;
                return View(p);
            }
            else
            {
                String urlLogin = "/Personeel/PersoneelLogIn";
                return Redirect(urlLogin);
            }
        }

        public ActionResult ProductenInzien(String naam)
        {
            if (Session["LoggedInP"] != null)
            {

                ProductDBController sc = new ProductDBController();
                List<Product> producten = sc.getAllProducten(naam);
                return View(producten);
            }
            else
        {
                String urlLogin = "/Personeel/PersoneelLogIn";
                return Redirect(urlLogin);
            }
        }

        public ActionResult PersoneelInzien(int? personeelnr)
        {
            if (Session["LoggedInP"] != null)
            {

            PersoneelDBController pc = new PersoneelDBController();
            List<Personeel> personeel = pc.getAllPersoneel(personeelnr);
            return View(personeel);
        }
            else
            {
                String urlLogin = "/Personeel/PersoneelLogIn";
                return Redirect(urlLogin);
            }
        }

        public ActionResult PersoneelToegevoegd(String voorletters, String tussenvoegsel, String achternaam, String type, String wachtwoord)
        {
            if (Session["LoggedInP"] != null)
            {
                Personeel personeel = Session["LoggedInP"] as Personeel;
                personeel.setVoorletters(voorletters);
                personeel.setTussenvoegsel(tussenvoegsel);
                personeel.setAchternaam(achternaam);
                personeel.setType(type);
                personeel.setWachtwoord(wachtwoord);
                

                RegistrerenDBController registrerenController = new RegistrerenDBController();
                registrerenController.InsertPersoneel(personeel);

                return View(personeel);

            }
            else
            {
                String urlLogin = "/Personeel/PersoneelLogIn";
                return Redirect(urlLogin);
            }
          
        }
        public ActionResult BestellingenBeheren(int? bestellingnr)
        {
            if (Session["LoggedInP"] != null)
            {
                MijnBestellingenDBController sc = new MijnBestellingenDBController();
                List<Bestelling> bestelling = sc.getAllBestellingenByDate(bestellingnr);
                return View(bestelling);
            }
            else
            {
                String urlLogin = "/Personeel/PersoneelLogIn";
                return Redirect(urlLogin);
            }
        }



        public ActionResult StatusGewijzigd(String status)
        {
            Bestelling bestelling = new Bestelling();
            bestelling.setStatus(status);
            BestellingenBeherenDBController abc = new BestellingenBeherenDBController();
            abc.statusAanpassen(bestelling);

            return View();
        }

    }
}

Project The Greenery/TheGreenery/TheGreenery/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheGreenery.DBcontrollers;
using TheGreenery.Models;
using MySql.Data.MySqlClient;

namespace TheGreenery.Controllers
{
    public class ManagerController : DatabaseController
    {
        public ActionResult Ingelogd()
        {
            return View();
        }

        public ActionResult ProductenInzien(String naam)
        {
            ProductDBController sc = new ProductDBController();
            List<Product> producten = sc.getAllProducten(naam);
            return View(producten);
        }

        public ActionResult PersoneelInzien(int? personeelnr)
        {
            
            //return View(personeel);
            if (Session["LoggedInP"] != null)
            {
                PersoneelDBController pc = new PersoneelDBController();
                List<Personeel> personeel = pc.getAllPersoneel(personeelnr);
                Personeel p = Session["LoggedInP"] as Personeel;

                return View(personeel);
            }
            else
            {
                String urlLogin = "/Personeel/PersoneelLogIn";
                return Redirect(urlLogin);
            }
        }

    }
}

Project The Greenery/TheGreenery/TheGreenery/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheGreenery.DBcontrollers;
using TheGreenery.Models;
using MySql.Data.MySqlClient;

namespace TheGreenery.Controllers
{
    public class ProductController : Controller
    {
        //
        // GET: /Product/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ShowProduct(String naam)
        {
            ProductDBController sc = new ProductDBController();
            List<Product> producten = sc.getAllProductenByNaam(naam);
            return View(producten);
        }

        public ActionResult LentePage(String lente)
        {

            LenteDBController sc = new LenteDBController();
            List<Product> producten = sc.getAllProductenByLente(lente);
            return View(producten);
        }

        public ActionResult ZomerPage(String zomer)
        {

            ZomerDBController sc = new ZomerDBController();

            List<Product> producten = sc.getAllProductenByZomer(zomer);
            return View(producten);
        }

        public ActionResult HerfstPage(String herfst)
        {

            HerfstDBController sc = new HerfstDBController();
            List<Product> producten = sc.getAllProductenByHerfst(herfst);

            return View(producten);
        }
        public ActionResult WinterPage(String winter)
        {

            WinterDBController sc = new WinterDBController();
            List<Product> producten = sc.getAllProductenByWinter(winter);

            return View(producten);
        }

    }
}

Project The Greenery/TheGreenery/TheGreenery/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MySql.Data.MySqlClient;
using System.Web.Security;
using TheGreenery.Models;
using TheGreenery.DBcontrollers;

namespace TheGreenery.Controllers
{
    public class UserController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LogIn()
        {
            return View();
        }

        public ActionResult LogOut()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult LoginResult(int? bestellingnr, String mail, String wachtwoord)
        {
            MijnBestellingenDBController bestellingen = new MijnBestellingenDBController();
            LoginDBController gebruiker = new LoginDBController();
            Session["LoggedIn"] = null;
            Klant gUser = gebruiker.LogInSelect(mail, wachtwoord);
            //Bestelling gBestelling = bestellingen.getAllBestellingenByDate(bestellingnr);

            try
            {
                if (gUser != null)
                {
                    if (gUser.mail == @mail && gUser.wachtwoord == @wachtwoord)
                    {
                        Session["LoggedIn"] = gUser;

                        int k = gUser.klantnr;
                        String d = Convert.ToString(k);

                        Session["inlogklantnr"] = (d);
                        String url = "/Home/Index";

                        BestellenDBController bd = new BestellenDBController();
                        bd.insertLegeBestelling(k);
                        return Redirect(url);
                    }

                }
            }

            catch (FormatException)
            {
                ViewData["Ero"] = "you dun goofed";
                return View("LogIn");
            }
            return View();
        }

        public ActionResult Registreer()
        {
            return View();
        }

        public ActionResult geregistreerd(String voorletters, String tussenvoegsel, String achternaam, String adres, String postcode, String woonplaats, String telefoonnr, String mail, String wachtwoord, String wachtwoord_herhalen)
        {
            Klant klant = new Klant();
            klant.setVoorletters(voorletters);
            klant.setTussenvoegsel(tussenvoegsel);
            klant.setAdres(adres);
            klant.setAchternaam(achternaam);
            klant.setPostocde(postcode);
            klant.setWoonplaats(woonplaats);
            klant.setTelefoonnr(telefoonnr);
            klant.setMail(mail);
            klant.setWachtwoord(wachtwoord);
            klant.setWachtwoordHerhalen(wachtwoord_herhalen);

            if (mail != null && !mail.Equals(""))
            {
                RegistrerenDBController registrerenController = new RegistrerenDBController();
                registrerenController.InsertRegistratie(klant);

            }
            return View();

        }

        public ActionResult GegevensGewijzigd(String voorletters, String tussenvoegsel, String achternaam, String adres, String postcode, String woonplaats, String telefoonnr, String mail)
        {
            Klant klant = new Klant();

            klant.setVoorletters(voorletters);
            klant.setTussenvoegsel(tussenvoegsel);
            klant.setAdres(adres);
            klant.setAchternaam(achternaam);
            klant.setPostocde(postcode);
            klant.setWoonplaats(woonplaats);
            klant.setTelefoonnr(telefoonnr);
            klant.setMail(mail);

            MijnGegevensDBController MijnGegevens = new MijnGegevensDBController();
            MijnGegevens.GegevensAanpassen(klant);

            return View();

        }

        public ActionResult MijnGegevens()
        {
            if (Session["LoggedIn"] != null)
            {
                Klant k = Session["LoggedIn"] as Klant;

                return View(k);
            }
            else
            {
                String urlLogin = "/User/LogIn";
                return Redirect(urlLogin);
            }

        }

        public ActionResult MijnBestellingen(int? bestellingnr)
        {
            if (Session["LoggedIn"] != null)
            {
                         
            
                MijnBestellingenDBController sc = new MijnBestellingenDBController();
                List<Bestelling> bestelling = sc.getAllBestellingenByDate(bestellingnr);
                return View(bestelling);
            }
            
            else 
            {
                String urlLogin = "/User/LogIn";
                return Redirect(urlLogin);
            }

        }
    }
}

Project The Greenery/TheGreenery/TheGreenery/Views/Shared/_Layout_Beheerder.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - The Greenery</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @System.Web.Optimization.Styles.Render("~/Content/Site.css")
</head>
<body>

    @if (Session["LoggedInP"] != null)
    {
        @Html.ActionLink("Mijn Gegevens", "MijnGegevens", "Personeel")
        <span> | </span>
        @Html.ActionLink("Log Out", "Logout", "Personeel")
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <a href="@Url.Action("Index","Home")"><img src="@Url.Content("~/Images/logo.png")" alt="Home" /></a>
                </div>
                <div class="float-right">
                    <section id="login">
                        <div style="float:right">
                            <form naam="input" action="@Url.Action("Showproduct", "Product")" method="post">
                                <input type=text name="naam" placeholder="zoekproduct" />
                                <input type="submit" value="zoeken" />
                            </form>
                        </div>
                    </section>
                    <div style="float:right" id="menu">
                        <div style="float:left"><a href="@Url.Action("Winkelwagen", "Home") "> <img border="0" alt="Greenery" src="~/Images/winkelwagen.png" /></a></div>
                        <div style="float:left">@Html.ActionLink("Home", "Index", "Home")</div>
                        <div style="float:left">@Html.ActionLink("  Over Ons", "About", "Home")</div>
                        <div style="float:left">@Html.ActionLink("  Contact", "Contact", "Home")</div>
                        <div style="float:left">@Html.ActionLink("wagen", "BestellingOverzicht", "Winkelwagen")</div>
                    </div>

                </div>
            </div>
        </header>
        <nav>
            <hr width="100%" align="right" size="0" />
            @using (Html.BeginForm())
            {
                <div id="menubalkb">
                    <div style="float:left">  <a href="@Url.Action("ProductenToevoegen", "Beheerder") "><img width="160" height="40" img border="0" alt="Greenery" src="~/Images/button_productToevoegen.png" /> </a></div>
                    <div style="float:left">  <a href="@Url.Action("ProductenBewerken", "Beheerder") "><img width="160" height="40" img border="0" alt="Greenery" src="~/Images/button_productWijzigen.png" /> </a></div>
                    <div style="float:left">  <a href="@Url.Action("ProductenInzien", "Beheerder") "><img width="160" height="40" img border="0" alt="Greenery" src="~/Images/button_ProductenInzien.png" /> </a></div>
                    <div style="float:left">  <a href="@Url.Action("PersoneelToevoegen", "Beheerder") "><img width="160" height="40" img border="0" alt="Greenery" src="~/Images/button_PersoneelToevoegen.png" /> </a></div>
                    <div style="float:left">  <a href="@Url.Action("PersoneelInzien", "Beheerder") "><img width="160" height="40" img border="0" alt="Greenery" src="~/Images/button_PersoneelInzien.png" /> </a></div>
                    <div style="float:left">  <a href="@Url.Action("BestellingenBeheren", "Beheerder") "><img width="160" height="40" img border="0" alt="Greenery" src="~/Images/button_BestellingBeheren.png" /> </a></div>
                </div>
            }
            <hr width="100%" align="right" size="0" />
        </nav>

    }

    else
    {
        @Html.ActionLink("Register", "Registreer", "Home")
        <span> | </span>
        @Html.ActionLink("Log In", "Login", "User")
        <span> | </span>
        @Html.ActionLink("Personeel Log In", "PersoneelLogIn", "Personeel")

        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <a href="@Url.Action("Index","Home")"><img src="@Url.Content("~/Images/logo.png")" alt="Home" /></a>
                </div>
                <div class="float-right">
                    <section id="login">
                        <div style="float:right">
                            <form naam="input" action="@Url.Action("Showproduct", "Product")" method="post">
                                <input type=text name="naam" placeholder="zoekproduct" />
                                <input type="submit" value="zoeken" />
                            </form>
                        </div>
                    </section>
                    <div style="float:right" id="menu">
                        <div style="float:left"><a href="@Url.Action("Winkelwagen", "Home") "> <img border="0" alt="Greenery" src="~/Images/winkelwagen.png" /></a></div>
                        <div style="float:left">@Html.ActionLink("Home", "Index", "Home")</div>
                        <div style="float:left">@Html.ActionLink("  Over Ons", "About", "Home")</div>
                        <div style="float:left">@Html.ActionLink("  Contact", "Contact", "Home")</div>
                        <div style="float:left">@Html.ActionLink("wagen", "BestellingOverzicht", "Winkelwagen")</div>
                    </div>

                </div>
            </div>
        </header>
        <nav>
            <hr width="100%" align="right" size="0" />
            @using (Html.BeginForm())
            {
                <div id="menubalkb">
                    <div style="float:left">  <a href="@Url.Action("ProductenToevoegen", "Beheerder") "><img width="160" height="40" img border="0" alt="Greenery" src="~/Images/button_productToevoegen.png" /> </a></div>
                    <div style="float:left">  <a href="@Url.Action("ProductenBewerken", "Beheerder") "><img width="160" height="40" img border="0" alt="Greenery" src="~/Images/button_productWijzigen.png" /> </a></div>
                    <div style="float:left">  <a href="@Url.Action("ProductenInzien", "Beheerder") "><img width="160" height="40" img border="0" alt="Greenery" src="~/Images/button_ProductenInzien.png" /> </a></div>
                    <div style="float:left">  <a href="@Url.Action("PersoneelToevoegen", "Beheerder") "><img width="160" height="40" img border="0" alt="Greenery" src="~/Images/button_PersoneelToevoegen.png" /> </a></div>
                    <div style="float:left">  <a href="@Url.Action("PersoneelInzien", "Beheerder") "><img width="160" height="40" img border="0" alt="Greenery" src="~/Images/button_PersoneelInzien.png" /> </a></div>
                </div>
            }
            <hr width="100%" align="right" size="0" />
        </nav>

    }

    @RenderSection("featured", required: false)
    <section class="content-wrapper main-content clear-fix">
        @RenderBody()
    </section>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>
                    &copy; @DateTime.Now.Year - The Greenery
                    @Html.ActionLink("AlgemeneVoorwaarden", "AlgemeneVoorwaarden", "Home") &nbsp; &nbsp; @Html.ActionLink("Privacypolicy", "Privacypolicy", "Home") &nbsp; &nbsp; @Html.ActionLink("FAQ", "FAQ", "Home")
            </div>
        </div>
        <div style="float:right"> <img width="90" height="90" border="0" alt="Greenery" src="~/Images/ekokeurmerk.jpg"><img /></div>
    </footer>
</body>
</html>

Project The Greenery/TheGreenery/TheGreenery/Views/Shared/_Layout_Manager.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - The Greenery</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @System.Web.Optimization.Styles.Render("~/Content/Site.css")
</head>
<body>

    @if (Session["LoggedInP"] != null)
    {
        @Html.ActionLink("Mijn Gegevens", "MijnGegevens", "Personeel")
        <span> | </span>
        @Html.ActionLink("Log Out", "Logout", "Personeel")
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <a href="@Url.Action("Index","Home")"><img src="@Url.Content("~/Images/logo.png")" alt="Home" /></a>
                </div>
                <div class="float-right">
                    <section id="login">
                        <div style="float:right">
                            <form naam="input" action="@Url.Action("Showproduct", "Product")" method="post">
                                <input type=text name="naam" placeholder="zoekproduct" />
                                <input type="submit" value="zoeken" />
                            </form>
                        </div>
                    </section>
                    <div style="float:right" id="menu">
                        <div style="float:left"><a href="@Url.Action("Winkelwagen", "Home") "> <img border="0" alt="Greenery" src="~/Images/winkelwagen.png" /></a></div>
                        <div style="float:left">@Html.ActionLink("Home", "Index", "Home")</div>
                        <div style="float:left">@Html.ActionLink("  Over Ons", "About", "Home")</div>
                        <div style="float:left">@Html.ActionLink("  Contact", "Contact", "Home")</div>
                        <div style="float:left">@Html.ActionLink("wagen", "BestellingOverzicht", "Winkelwagen")</div>
                    </div>

                </div>
            </div>
        </header>
        <nav>
            <hr width="100%" align="right" size="0" />
            @using (Html.BeginForm())
            {
                <div id="menubalkb">
                    <div style="float:left">  <a href="@Url.Action("ProductenInzien", "Manager") "><img width="160" height="40" img border="0" alt="Greenery" src="~/Images/button_ProductenInzien.png" /> </a></div>
                    <div style="float:left">  <a href="@Url.Action("PersoneelInzien", "Manager") "><img width="160" height="40" img border="0" alt="Greenery" src="~/Images/button_PersoneelInzien.png" /> </a></div>
                </div>
            }
            <hr width="100%" align="right" size="0" />
        </nav>

    }

    else
    {
        @Html.ActionLink("Register", "Registreer", "Home")
        <span> | </span>
        @Html.ActionLink("Log In", "Login", "User")
        <span> | </span>
        @Html.ActionLink("Personeel Log In", "PersoneelLogIn", "Personeel")

        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <a href="@Url.Action("Index","Home")"><img src="@Url.Content("~/Images/logo.png")" alt="Home" /></a>
                </div>
                <div class="float-right">
                    <section id="login">
                        <div style="float:right">
                            <form naam="input" action="@Url.Action("Showproduct", "Product")" method="post">
                                <input type=text name="naam" placeholder="zoekproduct" />
                                <input type="submit" value="zoeken" />
                            </form>
                        </div>
                    </section>
                    <div style="float:right" id="menu">
                        <div style="float:left">  <a href="@Url.Action("ProductenInzien", "Manager") "><img width="160" height="40" img border="0" alt="Greenery" src="~/Images/button_ProductenInzien.png" /> </a></div>
                        <div style="float:left">  <a href="@Url.Action("PersoneelInzien", "Manager") "><img width="160" height="40" img border="0" alt="Greenery" src="~/Images/button_PersoneelInzien.png" /> </a></div>

                    </div>
                </div>
            </div>
        </header>
        <nav>
            <hr width="100%" align="right" size="0" />
            @using (Html.BeginForm())
            {
                <div id="menubalkb">
                    <div style="float:left">  <a href="@Url.Action("ProductenToevoegen", "Beheerder") "><img width="160" height="40" img border="0" alt="Greenery" src="~/Images/button_productToevoegen.png" /> </a></div>
                    <div style="float:left">  <a href="@Url.Action("ProductenBewerken", "Beheerder") "><img width="160" height="40" img border="0" alt="Greenery" src="~/Images/button_productWijzigen.png" /> </a></div>
                    <div style="float:left">  <a href="@Url.Action("ProductenInzien", "Beheerder") "><img width="160" height="40" img border="0" alt="Greenery" src="~/Images/button_ProductenInzien.png" /> </a></div>
                    <div style="float:left">  <a href="@Url.Action("PersoneelToevoegen", "Beheerder") "><img width="160" height="40" img border="0" alt="Greenery" src="~/Images/button_PersoneelToevoegen.png" /> </a></div>
                    <div style="float:left">  <a href="@Url.Action("PersoneelInzien", "Beheerder") "><img width="160" height="40" img border="0" alt="Greenery" src="~/Images/button_PersoneelInzien.png" /> </a></div>
                </div>
            }
            <hr width="100%" align="right" size="0" />
        </nav>

    }

    @RenderSection("featured", required: false)
    <section class="content-wrapper main-content clear-fix">
        @RenderBody()
    </section>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>
                    &copy; @DateTime.Now.Year - The Greenery
                    @Html.ActionLink("AlgemeneVoorwaarden", "AlgemeneVoorwaarden", "Home") &nbsp; &nbsp; @Html.ActionLink("Privacypolicy", "Privacypolicy", "Home") &nbsp; &nbsp; @Html.ActionLink("FAQ", "FAQ", "Home")
            </div>
        </div>
        <div style="float:right"> <img width="90" height="90" border="0" alt="Greenery" src="~/Images/ekokeurmerk.jpg"><img /></div>
    </footer>
</body>
</html>