Project The Greenery/TheGreenery/TheGreenery/Controllers/WinkelproductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheGreenery.Models;

namespace TheGreenery.Controllers
{
    public class WinkelproductController : Controller
    {
        //
        // GET: /Winkelproduct/

        public ActionResult Index()
        {
            //ViewBag.listProducts = this.ViewBag;
            return View();
        }

    }
}

Project The Greenery/TheGreenery/TheGreenery/Controllers/WinkelwagenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using TheGreenery.DBcontrollers;
using TheGreenery.Models;

namespace TheGreenery.Controllers
{
    public class WinkelwagenController : Controller
    {
        //
        // GET: /Winkelwagen/

        ProductDBController sc = new ProductDBController();
        Product product = new Product();

        public ActionResult Index()
        {
            return View();
        }

        private int isExisting(int productnr)
        {
            List<Product> productq = (List<Product>)Session["wagen"];
            for (int i = 0; i < productq.Count; i++)
                if (productq[i].productnr == productnr)
                    return i;
            return -1;
        }

        public ActionResult Delete(int productnr)
        {
            int index = isExisting(productnr);
            List<Product> productq = (List<Product>)Session["wagen"];
            productq.RemoveAt(index);
            Session["wagen"] = productq;
            return View("wagen");
        }

        public ActionResult Bestellingplaatsen(int productnr)
        {
            if (Session["wagen"] == null)
            {

              
                List<Product> productq = sc.getProductByProductNr(productnr);

                Session["wagen"] = productq;

            }
            foreach (Product product in (List<Product>)Session["wagen"])
            {
                double? z = product.prijsPerEenheid;
                String m = Convert.ToString(z);

                Session["prijspereenheid"] = (m);
            }

            string bbb = Session["prijspereenheid"].ToString();
            string abc = Session["inlogklantnr"].ToString();
            int x = Convert.ToInt32(abc);
            double vv = Convert.ToDouble(bbb);

            int k = 4;
            //double j = 4;

            BestellenDBController bd = new BestellenDBController();

            List<Bestelling> bestellinglist = bd.getBestellingByKlantNr(x);

            Session["bestel"] = bestellinglist;

            //string vbn = @Session["aantalEenheden"].ToString();

            foreach (Bestelling bestell in (List<Bestelling>)Session["bestel"])
            {
                int d = bestell.bestellingnr;

                bd.insertBestellingRegel(d, productnr, k, vv);
            }
            return View("wagen");
        }

        public ActionResult BestellingOverzicht()
        {
            if (Session["wagen"] == null)
            {
                return View("index");
            }
            else
            {
                List<Product> productq = (List<Product>)Session["wagen"];
            }
            return View("wagen");
        }


        public ActionResult definitieveBestellingplaatsen()
        {

            //List<Product> wagen = (List<Product>)Session["wagen"];
            //ViewBag.listProducts = wagen;

            MailMessage mail = new MailMessage();
            SmtpClient SmtpServer = new SmtpClient("smtp.gmail.com");

            mail.From = new MailAddress("thegreenerymailtest@gmail.com"); // van welke email account je een bericht verstuurd
            mail.To.Add("thegreenerymailtest@gmail.com"); // naar welk email acount je een mail naar toe wilt sturen
            mail.Subject = "Test Mail"; // onderwerp email
            mail.IsBodyHtml = true;

            mail.Body = "Bestelling geplaatst op: " + DateTime.Now.ToLongDateString();  // body van mail


            SmtpServer.Port = 587;
            SmtpServer.Credentials = new System.Net.NetworkCredential("thegreenerymailtest@gmail.com", "greenery2015"); // de email die een mail verstuurd inlog gegevens
            SmtpServer.EnableSsl = true;

            SmtpServer.Send(mail);

            return View("Index");
        }

    }
}

Project The Greenery/TheGreenery/TheGreenery/Views/Winkelwagen/Index.cshtml
@using TheGreenery.Controllers;

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>wagen</title>
</head>
<body>
    <div style="float:left" id="textabout">
        <table cellpadding="2" cellspacing="2" border="1">
            <tr>
                <th>Option</th>
                <th>productnr</th>
                <th>naam</th>
                <th>type</th>
                <th>lente</th>
                <th>zomer</th>
                <th>herfst</th>
                <th>winter</th>
                <th>prijsPerEenheid</th>
                <th>Eenheid</th>
                <th>omschrijving</th>
                <th>voorraadPerEenheid</th>
                <th>imageNaam</th>
                <th>aantal producten</th>
                <th>bestel knop onder</th>
            </tr>
        </table>
        <br /><b />
        @Html.ActionLink("Ga door winkelen", "Index", "Winkelproduct")
    </div>

</body>
</html>

Project The Greenery/TheGreenery/TheGreenery/Views/Winkelwagen/wagen.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using TheGreenery.Controllers;
@using TheGreenery.Models;
@model List<Product>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>wagen</title>
</head>
<body>
    <div style="float:left" id="textabout">
    <table cellpadding="2" cellspacing="2" border="1">
        <tr>
            <th>Option</th>
            <th>productnr</th>
            <th>naam</th>
            <th>type</th>
            <th>lente</th>
            <th>zomer</th>
            <th>herfst</th>
            <th>winter</th>
            <th>prijsPerEenheid</th>
            <th>Eenheid</th>
            <th>omschrijving</th>
            <th>voorraadPerEenheid</th>
            <th>imageNaam</th>
            <th>aantal producten</th>
            <th>bestel knop onder</th>
        </tr>

        @foreach (Product product in (List<Product>)Session["wagen"])
        {
            <tr>
                <td>@Html.ActionLink("Delete", "Delete", "Winkelwagen", new { productnr = product.productnr }, null)</td>
                <td>@product.productnr</td>
                <td>@product.naam</td>
                <td>@product.type</td>
                <td>@product.lente</td>
                <td>@product.zomer</td>
                <td>@product.herfst</td>
                <td>@product.winter</td>
                <td>@product.omschrijving</td>
                <td>@product.voorraadPerEenheid</td>
                <td><img width="200" height="150" src="~/Images/@product.imageNaam" /></td>
                <td>@product.aanbieding</td>
                @*<td>@Item.Productnr</td>*@
                <td align="center">@Html.ActionLink("definitieveBestellingplaatsen", "definitieveBestellingplaatsen", "Winkelwagen")</td>
                @*<td align="center">definitieveBestellingplaatsen</td>*@ 

            </tr>
        }
        <tr>
            <td align="right" colspan="5">Totaal aantal</td>
        </tr>
    </table>
    <br /><b />
    @Html.ActionLink("Ga door winkelen", "Index", "Home")
</div>

</body>
</html>